tools/obsolete-variables: add script
Add a script that outputs missing variables from
OE-Core/meta-yocto/BitBake, i.e. for which grepping returned nothing.

There are a few exceptions, which are listed in VAR_EXCEPTIONS.

The script currently returns:

  ERROR: Variable CVSDIR not found anywhere
  ERROR: Variable FIT_KERNEL_COMP_ALG_EXTENSION not found anywhere
  ERROR: Variable USERMOD_PARAMS not found anywhere

Link: https://patch.msgid.link/20260827-missing-variables-v1-1-7ec8b525b23b@bootlin.com
Signed-off-by: Antonin Godard <antonin.godard@bootlin.com>